reference: Zea_mays.AGPv4.dna.toplevel.unwrapped.nocontigs.reorderd
samples:
    RNA_B73_ear: RNA_B73_ear_all.fastq
    RNA_B73_leaf: RNA_B73_leaf_all.fastq
    RNA_B73_root: RNA_B73_root_all.fastq
    2-4_mm_from_tip_of_ear_primordium: 2-4_mm_from_tip_of_ear_primordium_all.fastq
    6-8_mm_from_tip_of_ear_primordium: 6-8_mm_from_tip_of_ear_primordium_all.fastq
    Cortex: Cortex_all.fastq
    embryos_20DAP: embryos_20DAP_all.fastq
    EMBRYOS: EMBRYOS_all.fastq
    endosperm_crown: endosperm_crown_all.fastq
    EZ: EZ_all.fastq
    Germinating_Kernels: Germinating_Kernels_all.fastq
    GROWTH_ZONE: GROWTH_ZONE_all.fastq_all.fastq
    Internode_6-7: Internode_6-7_all.fastq_all.fastq
    Internode_7-8: Internode_7-8_all.fastq_all.fastq
    mature_female_spikelets: mature_female_spikelets_all.fastq
    MATURE_LEAF_TISSUE_leaf: MATURE_LEAF_TISSUE_leaf_all.fastq
    Mature_pollen: Mature_pollen_all.fastq
    MZ: MZ_all.fastq
    pericarp_aleurone: pericarp_aleurone_all.fastq
    PR: PR_all.fastq
    silks: silks_all.fastq
    SR: SR_all.fastq
    STOMATAL_DIVISION_ZONE: STOMATAL_DIVISION_ZONE_all.fastq
    SYMMETRICAL_DIVISION_ZONE: SYMMETRICAL_DIVISION_ZONE_all.fastq
    Vegetative_Meristem_Surrounding_Tissue: Vegetative_Meristem_Surrounding_Tissue_all.fastq
    RNA_data_B73_tassel_rep6: RNA_data_B73_tassel_rep6_all.fastq
    RNA_data_B73_tassel_rep4: RNA_data_B73_tassel_rep4_all.fastq 
    RNA_data_B73_tassel_rep2: RNA_data_B73_tassel_rep2_all.fastq 
    RNA_data_B73_root_rep2: RNA_data_B73_root_rep2_all.fastq
    RNA_data_B73_root_rep1: RNA_data_B73_root_rep1_all.fastq
    RNA_data_B73_leaf_rep2: RNA_data_B73_leaf_rep2_all.fastq
    RNA_data_B73_leaf_rep1: RNA_data_B73_leaf_rep1_all.fastq
    RNA_data_B73_ear_rep4: RNA_data_B73_ear_rep4_all.fastq 
    RNA_data_B73_ear_rep3: RNA_data_B73_ear_rep3_all.fastq 
    RNA_data_B73_ear_rep2: RNA_data_B73_ear_rep2_all.fastq 
    RNA_data_B73_ear_rep1: RNA_data_B73_ear_rep1_all.fastq 
